# yaml-language-server: $schema=https://aka.ms/configuration-dsc-schema/0.2
# Reference: https://github.com/dotnet/aspnetcore/blob/main/docs/BuildFromSource.md
properties:
  resources:
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Notepad++
        allowPrerelease: true
      settings:
        id: Notepad++.Notepad++
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install ShareX
        allowPrerelease: true
      settings:
        id: ShareX.ShareX
        source: winget
  configurationVersion: 0.2.0